### ISSUE TITLE
Inconsistent parsing results for GloMax® Discover files

### ISSUE THREAD

**Issue by zinfin** [sphinxbio/platechain#19]
We have four .csv files from a GloMax Discover platereader and three of the four files are parsed correctly. Parsing output from PER-005_plate_3_Absorbance_QuickRead_Results.csv is incorrect. The platechain parser interpreted the the column numbers and some of the row names as machine vaules.  Attached you'll find the four input files from GloMax and the corresponding output from the platechain parser.  Any ideas on why one of the four plates parsed incorrectly?  Formatting across four input files appears identical.
[Parser_input_files.zip](https://github.com/user-attachments/files/17233778/Parser_input_files.zip)
[parser_outputs.zip](https://github.com/user-attachments/files/17233781/parser_outputs.zip)

**Comment by nlarusstone** [comment]
Hi @zinfin -- I just updated the models to more recent models which should perform better and be more consistent.

Note, however, that these LLMs are not 100% deterministic, which is likely why you saw it working for 3 of the plates and not for the last one. 

Please give it a try with the new models and see if that helps

**Comment by zinfin** [comment]
Works great! Thanks
